parent_config_to_override: "base_tags.yaml"
run_name: "harmbench_cot_tags_15e5"

iterations: 20

# Training settings
learning_rate: 1.5e-5

# Influence model settings
veto_prompt_type: "five_point"

# Formatting penalty settings
formatting_penalty_scale_factor: 1

# Ground truth settings
use_ground_truth_scoring: false

# Qwen-specific settings
model_names:
  agent: "Qwen/Qwen3-8B"
  env: "Qwen/Qwen3-8B"

env_class: "harmbench-cot-tags"
